apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: node-labels-copier
    app.kubernetes.io/name: node-labels-copier
    app: node-labels-copier
    k8s-app: node-labels-copier
  name: node-labels-copier
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: node-labels-copier
      app.kubernetes.io/name: node-labels-copier
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: node-labels-copier
        app.kubernetes.io/name: node-labels-copier
        app: node-labels-copier
        k8s-app: node-labels-copier
    spec:
      containers:
      - name: controller
        image: ghcr.io/orangeappsru/node-labels-copier:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 50m
            memory: 20Mi
          requests:
            cpu: 50m
            memory: 20Mi
      serviceAccountName: node-labels-copier
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: node-labels-copier
    app.kubernetes.io/name: node-labels-copier
    app: node-labels-copier
    k8s-app: node-labels-copier
  name: node-labels-copier
rules:
- apiGroups:
  - ""
  resources:
   - nodes
  verbs:
  - get
  - list
  - watch
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: node-labels-copier
    app.kubernetes.io/name: node-labels-copier
    app: node-labels-copier
    k8s-app: node-labels-copier
  name: node-labels-copier
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-labels-copier
subjects:
- kind: ServiceAccount
  name: node-labels-copier
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: node-labels-copier
    app.kubernetes.io/name: node-labels-copier
    app: node-labels-copier
    k8s-app: node-labels-copier
  name:  node-labels-copier
  namespace: kube-system
